version: '2.1'
services:

  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: gobarberDB
    volumes:
      - ./var/lib/postgresql/data
    ports:
    - "15432:5432"
    networks:
    - dev-network

  mongodb:
    image: mongo
    volumes:
      - ./var/lib/mongoDb/data
    ports:
    - "27017:27017"
    networks:
    - dev-network

  redisbarber:
    image: redis:alpine
    volumes:
      - ./var/lib/redis/data
    ports:
      - "6379:6379"
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge
